// const restaurantDataArray = [
//     {
//       name: "Udipi Gokula",
//       rating: 4.5,
//       deliveryTime: "30-40 min",
//       cuisine: "South Indian",
//       address: "Bellandur, Karnataka",
//       imageSrc: "./Images/restaurant2.avif",
//     },
//     {
//       name: "Spice Junction",
//       rating: 3.8,
//       deliveryTime: "25-35 min",
//       cuisine: "North Indian",
//       address: "Koramangala, Bangalore",
//       imageSrc: "./Images/restaurant2.avif",
//     },
//     {
//       name: "Chilli Bites",
//       rating: 4.2,
//       deliveryTime: "20-30 min",
//       cuisine: "Chinese",
//       address: "Indiranagar, Bangalore",
//       imageSrc: "./Images/restaurant3.avif",
//     },
//     {
//       name: "Dosa Delight",
//       rating: 4.0,
//       deliveryTime: "35-45 min",
//       cuisine: "South Indian",
//       address: "Whitefield, Bangalore",
//       imageSrc: "./Images/restaurant4.avif",
//     },
//     {
//       name: "Pizza Paradise",
//       rating: 4.8,
//       deliveryTime: "15-25 min",
//       cuisine: "Italian",
//       address: "Electronic City, Bangalore",
//       imageSrc: "./Images/restaurant5.avif",
//     },
//     {
//       name: "Biryani Haven",
//       rating: 4.3,
//       deliveryTime: "40-50 min",
//       cuisine: "Biryani",
//       address: "Marathahalli, Bangalore",
//       imageSrc: "./Images/restaurant2.avif",
//     },
//     {
//         name: "Pizza Paradise",
//         rating: 4.8,
//         deliveryTime: "15-25 min",
//         cuisine: "Italian",
//         address: "Electronic City, Bangalore",
//         imageSrc: "./Images/restaurant5.avif",
//       },
//       {
//         name: "Biryani Haven",
//         rating: 4.3,
//         deliveryTime: "40-50 min",
//         cuisine: "Biryani",
//         address: "Marathahalli, Bangalore",
//         imageSrc: "./Images/restaurant2.avif",
//       },
//       {
//         name: "Pizza Paradise",
//         rating: 4.8,
//         deliveryTime: "15-25 min",
//         cuisine: "Italian",
//         address: "Electronic City, Bangalore",
//         imageSrc: "./Images/restaurant5.avif",
//       },
//       {
//         name: "Biryani Haven",
//         rating: 4.3,
//         deliveryTime: "40-50 min",
//         cuisine: "Biryani",
//         address: "Marathahalli, Bangalore",
//         imageSrc: "./Images/restaurant2.avif",
//       },
//       {
//         name: "Pizza Paradise",
//         rating: 4.8,
//         deliveryTime: "15-25 min",
//         cuisine: "Italian",
//         address: "Electronic City, Bangalore",
//         imageSrc: "./Images/restaurant5.avif",
//       }
//   ];
  
//   export default restaurantDataArray;
  

const restaurantDataArray = [
  {
    name: "Udipi Gokula",
    rating: 4.5,
    deliveryTime: "30-40 min",
    cuisine: "South Indian",
    address: "Bellandur, Karnataka",
    imageSrc: "./Images/restaurant2.avif",
    menu: [
      { itemName: "Masala Dosa", price: 120 },
      { itemName: "Idli Sambar", price: 80 },
      { itemName: "Vada Pav", price: 100 },
      { itemName: "Bisi Bele Bath", price: 150 },
      { itemName: "Uttapam", price: 110 },
      { itemName: "Puliyogare", price: 130 },
      { itemName: "Rava Kesari", price: 90 },
      { itemName: "Filter Coffee", price: 50 },
      { itemName: "Mysore Pak", price: 70 },
      { itemName: "Neer Dosa", price: 100 },
      { itemName: "Ragi Mudde", price: 80 },
      { itemName: "Ghee Roast", price: 130 },
    ],
  },
  {
    name: "Spice Junction",
    rating: 3.8,
    deliveryTime: "25-35 min",
    cuisine: "North Indian",
    address: "Koramangala, Bangalore",
    imageSrc: "./Images/restaurant2.avif",
    menu: [
      { itemName: "Butter Chicken", price: 180 },
      { itemName: "Paneer Tikka", price: 150 },
      { itemName: "Dal Makhani", price: 120 },
      { itemName: "Aloo Gobi", price: 100 },
      { itemName: "Chicken Biryani", price: 200 },
      { itemName: "Naan", price: 40 },
      { itemName: "Gulab Jamun", price: 60 },
      { itemName: "Lassi", price: 70 },
      { itemName: "Rajma Chawal", price: 130 },
      { itemName: "Tandoori Roti", price: 30 },
      { itemName: "Vegetable Biryani", price: 160 },
      { itemName: "Shahi Paneer", price: 140 },
    ],
  },
  {
    name: "Chilli Bites",
    rating: 4.2,
    deliveryTime: "20-30 min",
    cuisine: "Chinese",
    address: "Indiranagar, Bangalore",
    imageSrc: "./Images/restaurant3.avif",
    menu: [
      { itemName: "Manchurian", price: 90 },
      { itemName: "Fried Rice", price: 80 },
      { itemName: "Chilli Chicken", price: 120 },
      { itemName: "Hakka Noodles", price: 100 },
      { itemName: "Spring Rolls", price: 70 },
      { itemName: "Sweet Corn Soup", price: 60 },
      { itemName: "Schezwan Prawns", price: 150 },
      { itemName: "Vegetable Momos", price: 50 },
      { itemName: "Kung Pao Chicken", price: 130 },
      { itemName: "Hot and Sour Soup", price: 65 },
      { itemName: "Peking Duck", price: 200 },
      { itemName: "Dim Sum Platter", price: 180 },
    ],
  },
  {
    name: "Dosa Delight",
    rating: 4.0,
    deliveryTime: "35-45 min",
    cuisine: "South Indian",
    address: "Whitefield, Bangalore",
    imageSrc: "./Images/restaurant4.avif",
    menu: [
      { itemName: "Mysore Masala Dosa", price: 130 },
      { itemName: "Set Dosa", price: 110 },
      { itemName: "Ragi Dosa", price: 120 },
      { itemName: "Onion Rava Dosa", price: 140 },
      { itemName: "Paper Masala Dosa", price: 150 },
      { itemName: "Coconut Chutney", price: 40 },
      { itemName: "Pongal", price: 100 },
      { itemName: "Tomato Uttapam", price: 80 },
      { itemName: "Mango Lassi", price: 60 },
      { itemName: "Keerai Vadai", price: 70 },
      { itemName: "Pesarattu", price: 90 },
      { itemName: "Avial", price: 80 },
    ],
  },
  {
    name: "Pizza Paradise",
    rating: 4.8,
    deliveryTime: "15-25 min",
    cuisine: "Italian",
    address: "Electronic City, Bangalore",
    imageSrc: "./Images/restaurant5.avif",
    menu: [
      { itemName: "Margherita Pizza", price: 180 },
      { itemName: "Pepperoni Pizza", price: 200 },
      { itemName: "Vegetarian Supreme Pizza", price: 220 },
      { itemName: "Hawaiian Pizza", price: 190 },
      { itemName: "BBQ Chicken Pizza", price: 210 },
      { itemName: "Pasta Carbonara", price: 150 },
      { itemName: "Garlic Bread", price: 70 },
      { itemName: "Tiramisu", price: 90 },
      { itemName: "Caprese Salad", price: 120 },
      { itemName: "Calzone", price: 160 },
      { itemName: "Risotto", price: 130 },
      { itemName: "Cannoli", price: 80 },
    ],
  },
  {
    name: "Biryani Haven",
    rating: 4.3,
    deliveryTime: "40-50 min",
    cuisine: "Biryani",
    address: "Marathahalli, Bangalore",
    imageSrc: "./Images/restaurant2.avif",
    menu: [
      { itemName: "Chicken Biryani", price: 200 },
      { itemName: "Mutton Biryani", price: 220 },
      { itemName: "Veg Biryani", price: 180 },
      { itemName: "Egg Biryani", price: 190 },
      { itemName: "Hyderabadi Dum Biryani", price: 250 },
      { itemName: "Raita", price: 60 },
      { itemName: "Salan", price: 70 },
      { itemName: "Gulab Jamun", price: 80 },
      { itemName: "Kheer", price: 100 },
      { itemName: "Chicken 65", price: 150 },
      { itemName: "Paneer Tikka", price: 160 },
      { itemName: "Sheer Khurma", price: 120 },
      { itemName: "Keema Biryani", price: 210 },
      { itemName: "Dum Pukht Biryani", price: 230 },
      { itemName: "Bagara Baingan", price: 100 },
    ],
  },
  {
    name: "Veggie Delight",
    rating: 4.0,
    deliveryTime: "25-35 min",
    cuisine: "Vegetarian",
    address: "Jayanagar, Bangalore",
    imageSrc: "./Images/restaurant5.avif",
    menu: [
      { itemName: "Paneer Butter Masala", price: 150 },
      { itemName: "Vegetable Biryani", price: 120 },
      { itemName: "Gobi Manchurian", price: 100 },
      { itemName: "Palak Paneer", price: 130 },
      { itemName: "Dal Tadka", price: 90 },
      { itemName: "Mixed Veg Curry", price: 110 },
      { itemName: "Aloo Paratha", price: 60 },
      { itemName: "Chana Masala", price: 80 },
      { itemName: "Mushroom Tikka", price: 70 },
      { itemName: "Bhindi Masala", price: 80 },
      { itemName: "Masala Chai", price: 40 },
    ],
  },
  {
    name: "Sushi Express",
    rating: 4.5,
    deliveryTime: "30-40 min",
    cuisine: "Japanese",
    address: "Kalyan Nagar, Bangalore",
    imageSrc: "./Images/restaurant2.avif",
    menu: [
      { itemName: "Sashimi Platter", price: 180 },
      { itemName: "California Roll", price: 200 },
      { itemName: "Tempura Udon", price: 220 },
      { itemName: "Teriyaki Chicken", price: 190 },
      { itemName: "Dragon Roll", price: 210 },
      { itemName: "Miso Soup", price: 150 },
      { itemName: "Edamame", price: 70 },
      { itemName: "Chirashi Bowl", price: 90 },
      { itemName: "Green Tea Ice Cream", price: 120 },
      { itemName: "Wasabi Prawns", price: 160 },
      { itemName: "Rainbow Sushi", price: 130 },
    ],
  },
  {
    name: "Kebab Kingdom",
    rating: 4.2,
    deliveryTime: "20-30 min",
    cuisine: "Mughlai",
    address: "Malleshwaram, Bangalore",
    imageSrc: "./Images/restaurant6.avif",
    menu: [
      { itemName: "Seekh Kebab", price: 90 },
      { itemName: "Chicken Biryani", price: 120 },
      { itemName: "Mutton Korma", price: 100 },
      { itemName: "Paneer Tikka", price: 130 },
      { itemName: "Murg Malai Kebab", price: 70 },
      { itemName: "Galouti Kebab", price: 110 },
      { itemName: "Shahi Tandoori Roti", price: 40 },
      { itemName: "Awadhi Dum Biryani", price: 80 },
      { itemName: "Zafrani Pulao", price: 60 },
      { itemName: "Lassi", price: 70 },
      { itemName: "Gulab Jamun", price: 50 },
    ],
  },
  {
    name: "Mediterranean Delight",
    rating: 4.8,
    deliveryTime: "15-25 min",
    cuisine: "Mediterranean",
    address: "Kengeri, Bangalore",
    imageSrc: "./Images/restaurant10.avif",
    menu: [
      { itemName: "Hummus with Pita", price: 180 },
      { itemName: "Falafel Wrap", price: 200 },
      { itemName: "Greek Salad", price: 220 },
      { itemName: "Shawarma", price: 190 },
      { itemName: "Moussaka", price: 210 },
      { itemName: "Tabbouleh", price: 150 },
      { itemName: "Baba Ganoush", price: 70 },
      { itemName: "Spanakopita", price: 90 },
      { itemName: "Baklava", price: 120 },
      { itemName: "Grilled Halloumi", price: 160 },
      { itemName: "Lemon Mint Cooler", price: 130 },
    ],
  },
  {
    name: "Street Food Haven",
    rating: 4.3,
    deliveryTime: "40-50 min",
    cuisine: "Street Food",
    address: "Shivajinagar, Bangalore",
    imageSrc: "./Images/restaurant3.avif",
    menu: [
      { itemName: "Pav Bhaji", price: 80 },
      { itemName: "Pani Puri", price: 50 },
      { itemName: "Bhel Puri", price: 60 },
      { itemName: "Vada Pav", price: 40 },
      { itemName: "Samosa Chaat", price: 70 },
      { itemName: "Kathi Roll", price: 90 },
      { itemName: "Dabeli", price: 80 },
      { itemName: "Chole Bhature", price: 100 },
      { itemName: "Kulfi Falooda", price: 120 },
      { itemName: "Jalebi with Rabri", price: 70 },
      { itemName: "Chai", price: 20 },
    ],
  },
  // Add more restaurants and their menus as needed
];

export default restaurantDataArray;
